<?php
namespace Hi\Installer\Api;


use Composer\Package\PackageInterface;
use Composer\Repository\InstalledRepositoryInterface;
use Hi\Helpers\Console;

final class Installer extends \Hi\Installer\Site\Installer
{
    protected $installerName = 'Novum api installer';
    function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        $oConsole = new Console($this->io);
        $oConsole->log('Site installation completed', $this->installerName);
        parent::install($repo, $package); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritDoc}
     */
    public function supports($packageType)
    {
        return 'novum-api' === $packageType || 'hurah-api' === $packageType ;
    }
}
